import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import {ClerkProvider} from '@clerk/nextjs';

const roboto = Roboto({
  weight: ['500' , '400' , '300' , '900' , '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Projectrr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
    appearance={{
      layout: {
        socialButtonsVariant: 'iconButton',
      }
    }}
    >
      
      <html lang="en">
        <body className={roboto.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
